[arrangement]
name = "custom_barcode" # Leave this as is

mask1_front = "" # Don't change me. Outer adapter that is in front of the barcode sequence. Should be blank because by now barcode is at front of read.
mask1_rear = "AGTCAGTCAGATGCTGCGTTCTTCATCGATGC" # This is for ITS (REV). Change me for different construct. This is the pad, linker, primer that are after the barcode sequence

# Barcode sequences
barcode1_pattern = "BC%03i" # Don't change me.
first_index = 1 # Don't change me.
last_index = 8 # CHANGE ME! Change to the total number of barcodes you have in the run.

## Scoring options
[scoring]
max_barcode_penalty = 1 # Don't change me. This is the number of mismatches allowed. We probably don't want any more than 1.
min_barcode_penalty_dist = 1 # Maybe change me. How much better must the best option be compared to 2nd best.
min_separation_only_dist = 100 # Don't change me. This is set to a high number so it is ignored.
min_flank_score = 0.5 # Maybe change me. 0.5 is the default. Increase for a more stringent alignment with flank seqs.
flank_left_pad = 0 # Don't change me. Setting to 0 means it will just use the barcode alignment and none of the flank seqs.
flank_right_pad = 0 # Don't change me. Setting to 0 means it will just use the barcode alignment and none of the flank seqs.
